import '@/styles/globals.scss';

import type { Metadata } from 'next';

import favicon from '@/assets/favicon.ico';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={favicon.src} />
      </head>
      <body>{children}</body>
    </html>
  );
}
